NETWORK_CONTEXT_SETTING_MAX_CONNECTION_ATTEMPTS_PER_REQUEST = 0
NETWORK_CONTEXT_SETTING_MAX_RETRIES_PER_REQUEST = 1
NETWORK_CONTEXT_SETTING_CONNECTION_ERROR_TIMEOUT = 2
NETWORK_CONTEXT_SETTING_CONNECTION_ERROR_RETRY_WAIT = 3
NETWORK_CONTEXT_SETTING_CONNECTION_INACTIVITY_TIMEOUT = 4
NETWORK_CONTEXT_SETTING_SERVERSIDE_BANDIWIDTH_RETRY_WAIT = 5
NETWORK_CONTEXT_SETTING_NETWORK_INFRASTRUCTURE_PROBLEMS_HALT_VELOCITY = 6
NETWORK_CONTEXT_SETTING_MAX_ACTIVE_NETWORK_JOBS = 7
NETWORK_CONTEXT_SETTING_VERIFY_HTTPS_TRAFFIC = 8
NETWORK_CONTEXT_SETTING_CURL_CFFI_NAME = 9
# TODO: proxy stuff
# TODO: what to do with 400, 403, 404, 501, 503, including back-out-and-retry-later tech levers

network_context_setting_enum_str_lookup = {
    NETWORK_CONTEXT_SETTING_MAX_CONNECTION_ATTEMPTS_PER_REQUEST : 'max connection attempts per request',
    NETWORK_CONTEXT_SETTING_MAX_RETRIES_PER_REQUEST : 'max retries per request',
    NETWORK_CONTEXT_SETTING_CONNECTION_ERROR_TIMEOUT : 'connection error timeout',
    NETWORK_CONTEXT_SETTING_CONNECTION_ERROR_RETRY_WAIT : 'connection error/inactivity retry wait',
    NETWORK_CONTEXT_SETTING_CONNECTION_INACTIVITY_TIMEOUT : 'inactivity timeout',
    NETWORK_CONTEXT_SETTING_SERVERSIDE_BANDIWIDTH_RETRY_WAIT : 'serverside bandwidth retry wait',
    NETWORK_CONTEXT_SETTING_NETWORK_INFRASTRUCTURE_PROBLEMS_HALT_VELOCITY : 'network infrastructure error halt velocity',
    NETWORK_CONTEXT_SETTING_MAX_ACTIVE_NETWORK_JOBS : 'max number of simultaneous active network jobs',
    NETWORK_CONTEXT_SETTING_VERIFY_HTTPS_TRAFFIC : 'verify https traffic',
    NETWORK_CONTEXT_SETTING_CURL_CFFI_NAME : 'curl_cffi browser name',
}

NETWORK_CONTEXT_EVENT_NETWORK_INFRASTRUCTURE = 0
NETWORK_CONTEXT_EVENT_SERVERSIDE_BANDWIDTH = 1
# TODO: 503 stuff if we want, captcha gateways, whatever (but these are currently network infrastructure so we'd prob want to granularise it all to connectionerror, unknown server exception, etc...)
