name: Publish Docs 

on:
  push:
    branches:
      - master 

concurrency: 
  group: publish-docs
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-redirects mkdocs-git-revision-date-localized-plugin
      - run: mkdocs gh-deploy --force --config-file mkdocs-gh-pages.yml
